Repository uport-project/uport-connect, pull requests merged in 2018-06, with the labels that each got.

#139 Update usage guide for developer portal links
  README.md
  docs/guides/usage.md
Labels: review

#131 Fix autosigner
  karmawrapper.js
  package-lock.json
  package.json
  test/topicFactory.js
  test/uportWeb3.js
  utils/autosigner.js
  yarn.lock
Labels: bug, review

#142 Fix registration Url
  docs/reference/index.md
Labels: backlog
